### ISSUE TITLE
Use Base64 for images?

### ISSUE THREAD

**Issue by trosel** [brilliancebitcoin/nostrgram#9]
If someone pastes an image in the text box, convert it to a base64 string and send that as the nostr content.

On the client side, [check messages to see if they are base64 strings](https://stackoverflow.com/questions/8106038/regex-for-detecting-base64-encoded-strings) and if so, convert them to `<img>` elements

**Comment by brilliancebitcoin** [comment]
The strings you can upload to nostr relays are pretty limited. 128kb I think. I suspect most images would overflow that and thus be rejected. I suspect future client devs will host a server where users can upload images but I just don't want to deal with that. So it's a temporary problem, likely.
